# Generated by Django 3.2.5 on 2021-08-15 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationComment',
            fields=[
                ('username', models.CharField(max_length=150, primary_key=True, serialize=False)),
                ('real_name', models.CharField(max_length=255)),
                ('email_address', models.EmailField(max_length=254)),
                ('comment', models.TextField()),
            ],
        ),
    ]
